Feature/developer portal
udplabs/zartan pull request #445
Opened 2021-04-23 17:25 UTC by dzadikdev

Rebase with Master

2021-04-23 18:48 UTC, dzadikdev reviewed
Merge is good to go.

2021-04-23 20:46 UTC, noinarisak requested changes
You committed the merge conflict diff comments in this PR. Remove it and this good to go!

2021-04-23 20:46 UTC, noinarisak commented on GlobalBehaviorandComponents/templates/components/template-navigation-developer.html
> +>>>>>>> Add developer portal vertical
You committed the merge conflict diff comments. Please resolve.

2021-04-23 20:46 UTC, noinarisak commented on GlobalBehaviorandComponents/templates/components/template-navigation-developer.html
> +>>>>>>> WIP
You committed the merge conflict diff comments. Please resolve.

2021-04-23 20:46 UTC, noinarisak commented on GlobalBehaviorandComponents/templates/components/template-navigation-developer.html
> +>>>>>>> WIP
You committed the merge conflict diff comments. Please resolve.

2021-04-26 18:41 UTC, noinarisak commented
Looks better. Let me know if this is ready to merge @dzadikdev .

2021-04-26 21:07 UTC, dzadikdev commented
@noinarisak Ready to Merge

2021-04-28 15:21 UTC, noinarisak approved these changes

2021-04-28 15:21 UTC, merged