adds Sendgrid email support
udplabs/zartan pull request #466
Opened 2021-11-18 18:19 UTC by mdwallick

This is a very simple change to add Sendgrid support for emails.

2021-11-18 19:40 UTC, shawnrecinto-okta approved these changes
Follows thew same pattern as what we have for Sparkpost and AWS API
@noinarisak could you take a peek too?

2021-11-18 20:37 UTC, noinarisak requested changes
@mdwallick Can you also update [README](https://github.com/udplabs/zartan/tree/master/docs#local-environment-variables) to represent the new addition! Btw, great addition!

2021-11-18 21:14 UTC, noinarisak commented
Maybe one of these days, I create Adapter pattern to enable more Email Providers.

2021-11-19 13:39 UTC, mdwallick commented
I added Sendgrid documentation to the [README](https://github.com/udplabs/zartan/tree/master/docs#local-environment-variables).

2021-12-09 21:45 UTC, noinarisak commented
Thanks for the README update, @mdwallick! 

Looks like the build failed due to our linting check. 😉  Can you run flake8 locally or review the build [log](https://github.com/udplabs/zartan/runs/4476530661?check_suite_focus=true) and correct the issue and re-push the PR? Ping me on Slack if you need help.

2021-12-10 14:51 UTC, mdwallick commented
I've fixed the linting errors. My bad for not checking that first.

2021-12-14 21:09 UTC, noinarisak approved these changes

2021-12-14 21:10 UTC, noinarisak commented
Thanks @mdwallick 🌮 🎉 !!!

2021-12-14 21:10 UTC, merged